version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --trusted-host pypi.org urllib3[secure]
      - pip install --trusted-host pypi.org pyopenssl ndg-httpsclient pyasn1
      - python -m pip install --trusted-host pypi.org Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
